export { default as Hero } from './hero'
export { default as About } from './about'
export { default as Transition } from './transition'
export { default as Solutions } from './solutions'
export { default as Experience } from './experience'
export { default as Info } from './info'
export { default as FAQ } from './faq'
